spring:
  datasource:
    url: 'jdbc:h2:file:./data/cars'
    driver-class-name: org.h2.Driver
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect